// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnswerIdRouteImport } from './routes/answer.$id'
import { Route as WorldStoryIdRouteImport } from './routes/world.$storyId'

const IndexRoute = IndexRouteImport.update({
            id: '/',path: '/',getParentRoute: () => rootRouteImport
          })
const AnswerIdRoute = AnswerIdRouteImport.update({
            id: '/answer/$id',path: '/answer/$id',getParentRoute: () => rootRouteImport
          })
const WorldStoryIdRoute = WorldStoryIdRouteImport.update({
            id: '/world/$storyId',path: '/world/$storyId',getParentRoute: () => rootRouteImport
          })

const rootRouteChildren = {
  IndexRoute: IndexRoute,AnswerIdRoute: AnswerIdRoute,WorldStoryIdRoute: WorldStoryIdRoute
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)