/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnswerIdRouteImport } from './routes/answer.$id'
import { Route as WorldStoryIdRouteImport } from './routes/world.$storyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerIdRoute = AnswerIdRouteImport.update({
  id: '/answer/$id',
  path: '/answer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldStoryIdRoute = WorldStoryIdRouteImport.update({
  id: '/world/$storyId',
  path: '/world/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/answer/$id': typeof AnswerIdRoute
  '/world/$storyId': typeof WorldStoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/answer/$id': typeof AnswerIdRoute
  '/world/$storyId': typeof WorldStoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/answer/$id': typeof AnswerIdRoute
  '/world/$storyId': typeof WorldStoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/answer/$id' | '/world/$storyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/answer/$id' | '/world/$storyId'
  id: '__root__' | '/' | '/answer/$id' | '/world/$storyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnswerIdRoute: typeof AnswerIdRoute
  WorldStoryIdRoute: typeof WorldStoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer/$id': {
      id: '/answer/$id'
      path: '/answer/$id'
      fullPath: '/answer/$id'
      preLoaderRoute: typeof AnswerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/$storyId': {
      id: '/world/$storyId'
      path: '/world/$storyId'
      fullPath: '/world/$storyId'
      preLoaderRoute: typeof WorldStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnswerIdRoute: AnswerIdRoute,
  WorldStoryIdRoute: WorldStoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
